/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ql2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ql2.pb-c.h"
void   version_dummy__init
                     (VersionDummy         *message)
{
  static const VersionDummy init_value = VERSION_DUMMY__INIT;
  *message = init_value;
}
size_t version_dummy__get_packed_size
                     (const VersionDummy *message)
{
  assert(message->base.descriptor == &version_dummy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t version_dummy__pack
                     (const VersionDummy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &version_dummy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t version_dummy__pack_to_buffer
                     (const VersionDummy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &version_dummy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VersionDummy *
       version_dummy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VersionDummy *)
     protobuf_c_message_unpack (&version_dummy__descriptor,
                                allocator, len, data);
}
void   version_dummy__free_unpacked
                     (VersionDummy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &version_dummy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query__assoc_pair__init
                     (Query__AssocPair         *message)
{
  static const Query__AssocPair init_value = QUERY__ASSOC_PAIR__INIT;
  *message = init_value;
}
void   query__init
                     (Query         *message)
{
  static const Query init_value = QUERY__INIT;
  *message = init_value;
}
size_t query__get_packed_size
                     (const Query *message)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query__pack
                     (const Query *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query__pack_to_buffer
                     (const Query *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Query *
       query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Query *)
     protobuf_c_message_unpack (&query__descriptor,
                                allocator, len, data);
}
void   query__free_unpacked
                     (Query *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   frame__init
                     (Frame         *message)
{
  static const Frame init_value = FRAME__INIT;
  *message = init_value;
}
size_t frame__get_packed_size
                     (const Frame *message)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frame__pack
                     (const Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frame__pack_to_buffer
                     (const Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Frame *
       frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Frame *)
     protobuf_c_message_unpack (&frame__descriptor,
                                allocator, len, data);
}
void   frame__free_unpacked
                     (Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   backtrace__init
                     (Backtrace         *message)
{
  static const Backtrace init_value = BACKTRACE__INIT;
  *message = init_value;
}
size_t backtrace__get_packed_size
                     (const Backtrace *message)
{
  assert(message->base.descriptor == &backtrace__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t backtrace__pack
                     (const Backtrace *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &backtrace__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t backtrace__pack_to_buffer
                     (const Backtrace *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &backtrace__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Backtrace *
       backtrace__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Backtrace *)
     protobuf_c_message_unpack (&backtrace__descriptor,
                                allocator, len, data);
}
void   backtrace__free_unpacked
                     (Backtrace *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &backtrace__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   datum__assoc_pair__init
                     (Datum__AssocPair         *message)
{
  static const Datum__AssocPair init_value = DATUM__ASSOC_PAIR__INIT;
  *message = init_value;
}
void   datum__init
                     (Datum         *message)
{
  static const Datum init_value = DATUM__INIT;
  *message = init_value;
}
size_t datum__get_packed_size
                     (const Datum *message)
{
  assert(message->base.descriptor == &datum__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t datum__pack
                     (const Datum *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &datum__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t datum__pack_to_buffer
                     (const Datum *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &datum__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Datum *
       datum__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Datum *)
     protobuf_c_message_unpack (&datum__descriptor,
                                allocator, len, data);
}
void   datum__free_unpacked
                     (Datum *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &datum__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   term__assoc_pair__init
                     (Term__AssocPair         *message)
{
  static const Term__AssocPair init_value = TERM__ASSOC_PAIR__INIT;
  *message = init_value;
}
void   term__init
                     (Term         *message)
{
  static const Term init_value = TERM__INIT;
  *message = init_value;
}
size_t term__get_packed_size
                     (const Term *message)
{
  assert(message->base.descriptor == &term__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t term__pack
                     (const Term *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &term__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t term__pack_to_buffer
                     (const Term *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &term__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Term *
       term__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Term *)
     protobuf_c_message_unpack (&term__descriptor,
                                allocator, len, data);
}
void   term__free_unpacked
                     (Term *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &term__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue version_dummy__version__enum_values_by_number[5] =
{
  { "V1_0", "VERSION_DUMMY__VERSION__V1_0", 885177795 },
  { "V0_1", "VERSION_DUMMY__VERSION__V0_1", 1063369270 },
  { "V0_4", "VERSION_DUMMY__VERSION__V0_4", 1074539808 },
  { "V0_3", "VERSION_DUMMY__VERSION__V0_3", 1601562686 },
  { "V0_2", "VERSION_DUMMY__VERSION__V0_2", 1915781601 },
};
static const ProtobufCIntRange version_dummy__version__value_ranges[] = {
{885177795, 0},{1063369270, 1},{1074539808, 2},{1601562686, 3},{1915781601, 4},{0, 5}
};
static const ProtobufCEnumValueIndex version_dummy__version__enum_values_by_name[5] =
{
  { "V0_1", 1 },
  { "V0_2", 4 },
  { "V0_3", 3 },
  { "V0_4", 2 },
  { "V1_0", 0 },
};
const ProtobufCEnumDescriptor version_dummy__version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VersionDummy.Version",
  "Version",
  "VersionDummy__Version",
  "",
  5,
  version_dummy__version__enum_values_by_number,
  5,
  version_dummy__version__enum_values_by_name,
  5,
  version_dummy__version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue version_dummy__protocol__enum_values_by_number[2] =
{
  { "PROTOBUF", "VERSION_DUMMY__PROTOCOL__PROTOBUF", 656407617 },
  { "JSON", "VERSION_DUMMY__PROTOCOL__JSON", 2120839367 },
};
static const ProtobufCIntRange version_dummy__protocol__value_ranges[] = {
{656407617, 0},{2120839367, 1},{0, 2}
};
static const ProtobufCEnumValueIndex version_dummy__protocol__enum_values_by_name[2] =
{
  { "JSON", 1 },
  { "PROTOBUF", 0 },
};
const ProtobufCEnumDescriptor version_dummy__protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VersionDummy.Protocol",
  "Protocol",
  "VersionDummy__Protocol",
  "",
  2,
  version_dummy__protocol__enum_values_by_number,
  2,
  version_dummy__protocol__enum_values_by_name,
  2,
  version_dummy__protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
#define version_dummy__field_descriptors NULL
#define version_dummy__field_indices_by_name NULL
#define version_dummy__number_ranges NULL
const ProtobufCMessageDescriptor version_dummy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VersionDummy",
  "VersionDummy",
  "VersionDummy",
  "",
  sizeof(VersionDummy),
  0,
  version_dummy__field_descriptors,
  version_dummy__field_indices_by_name,
  0,  version_dummy__number_ranges,
  (ProtobufCMessageInit) version_dummy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query__assoc_pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Query__AssocPair, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Query__AssocPair, val),
    &term__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__assoc_pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange query__assoc_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor query__assoc_pair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Query.AssocPair",
  "AssocPair",
  "Query__AssocPair",
  "",
  sizeof(Query__AssocPair),
  2,
  query__assoc_pair__field_descriptors,
  query__assoc_pair__field_indices_by_name,
  1,  query__assoc_pair__number_ranges,
  (ProtobufCMessageInit) query__assoc_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue query__query_type__enum_values_by_number[5] =
{
  { "START", "QUERY__QUERY_TYPE__START", 1 },
  { "CONTINUE", "QUERY__QUERY_TYPE__CONTINUE", 2 },
  { "STOP", "QUERY__QUERY_TYPE__STOP", 3 },
  { "NOREPLY_WAIT", "QUERY__QUERY_TYPE__NOREPLY_WAIT", 4 },
  { "SERVER_INFO", "QUERY__QUERY_TYPE__SERVER_INFO", 5 },
};
static const ProtobufCIntRange query__query_type__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex query__query_type__enum_values_by_name[5] =
{
  { "CONTINUE", 1 },
  { "NOREPLY_WAIT", 3 },
  { "SERVER_INFO", 4 },
  { "START", 0 },
  { "STOP", 2 },
};
const ProtobufCEnumDescriptor query__query_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Query.QueryType",
  "QueryType",
  "Query__QueryType",
  "",
  5,
  query__query_type__enum_values_by_number,
  5,
  query__query_type__enum_values_by_name,
  1,
  query__query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const protobuf_c_boolean query__obsolete_noreply__default_value = 0;
static const protobuf_c_boolean query__accepts_r_json__default_value = 0;
static const ProtobufCFieldDescriptor query__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Query, has_type),
    offsetof(Query, type),
    &query__query_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Query, query),
    &term__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Query, has_token),
    offsetof(Query, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "OBSOLETE_noreply",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Query, has_obsolete_noreply),
    offsetof(Query, obsolete_noreply),
    NULL,
    &query__obsolete_noreply__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accepts_r_json",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Query, has_accepts_r_json),
    offsetof(Query, accepts_r_json),
    NULL,
    &query__accepts_r_json__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "global_optargs",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, n_global_optargs),
    offsetof(Query, global_optargs),
    &query__assoc_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__field_indices_by_name[] = {
  3,   /* field[3] = OBSOLETE_noreply */
  4,   /* field[4] = accepts_r_json */
  5,   /* field[5] = global_optargs */
  1,   /* field[1] = query */
  2,   /* field[2] = token */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Query",
  "Query",
  "Query",
  "",
  sizeof(Query),
  6,
  query__field_descriptors,
  query__field_indices_by_name,
  1,  query__number_ranges,
  (ProtobufCMessageInit) query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue frame__frame_type__enum_values_by_number[2] =
{
  { "POS", "FRAME__FRAME_TYPE__POS", 1 },
  { "OPT", "FRAME__FRAME_TYPE__OPT", 2 },
};
static const ProtobufCIntRange frame__frame_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex frame__frame_type__enum_values_by_name[2] =
{
  { "OPT", 1 },
  { "POS", 0 },
};
const ProtobufCEnumDescriptor frame__frame_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Frame.FrameType",
  "FrameType",
  "Frame__FrameType",
  "",
  2,
  frame__frame_type__enum_values_by_number,
  2,
  frame__frame_type__enum_values_by_name,
  1,
  frame__frame_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor frame__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Frame, has_type),
    offsetof(Frame, type),
    &frame__frame_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Frame, has_pos),
    offsetof(Frame, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Frame, opt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frame__field_indices_by_name[] = {
  2,   /* field[2] = opt */
  1,   /* field[1] = pos */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Frame",
  "Frame",
  "Frame",
  "",
  sizeof(Frame),
  3,
  frame__field_descriptors,
  frame__field_indices_by_name,
  1,  frame__number_ranges,
  (ProtobufCMessageInit) frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor backtrace__field_descriptors[1] =
{
  {
    "frames",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Backtrace, n_frames),
    offsetof(Backtrace, frames),
    &frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned backtrace__field_indices_by_name[] = {
  0,   /* field[0] = frames */
};
static const ProtobufCIntRange backtrace__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor backtrace__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Backtrace",
  "Backtrace",
  "Backtrace",
  "",
  sizeof(Backtrace),
  1,
  backtrace__field_descriptors,
  backtrace__field_indices_by_name,
  1,  backtrace__number_ranges,
  (ProtobufCMessageInit) backtrace__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response__response_type__enum_values_by_number[8] =
{
  { "SUCCESS_ATOM", "RESPONSE__RESPONSE_TYPE__SUCCESS_ATOM", 1 },
  { "SUCCESS_SEQUENCE", "RESPONSE__RESPONSE_TYPE__SUCCESS_SEQUENCE", 2 },
  { "SUCCESS_PARTIAL", "RESPONSE__RESPONSE_TYPE__SUCCESS_PARTIAL", 3 },
  { "WAIT_COMPLETE", "RESPONSE__RESPONSE_TYPE__WAIT_COMPLETE", 4 },
  { "SERVER_INFO", "RESPONSE__RESPONSE_TYPE__SERVER_INFO", 5 },
  { "CLIENT_ERROR", "RESPONSE__RESPONSE_TYPE__CLIENT_ERROR", 16 },
  { "COMPILE_ERROR", "RESPONSE__RESPONSE_TYPE__COMPILE_ERROR", 17 },
  { "RUNTIME_ERROR", "RESPONSE__RESPONSE_TYPE__RUNTIME_ERROR", 18 },
};
static const ProtobufCIntRange response__response_type__value_ranges[] = {
{1, 0},{16, 5},{0, 8}
};
static const ProtobufCEnumValueIndex response__response_type__enum_values_by_name[8] =
{
  { "CLIENT_ERROR", 5 },
  { "COMPILE_ERROR", 6 },
  { "RUNTIME_ERROR", 7 },
  { "SERVER_INFO", 4 },
  { "SUCCESS_ATOM", 0 },
  { "SUCCESS_PARTIAL", 2 },
  { "SUCCESS_SEQUENCE", 1 },
  { "WAIT_COMPLETE", 3 },
};
const ProtobufCEnumDescriptor response__response_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.ResponseType",
  "ResponseType",
  "Response__ResponseType",
  "",
  8,
  response__response_type__enum_values_by_number,
  8,
  response__response_type__enum_values_by_name,
  2,
  response__response_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue response__error_type__enum_values_by_number[8] =
{
  { "INTERNAL", "RESPONSE__ERROR_TYPE__INTERNAL", 1000000 },
  { "RESOURCE_LIMIT", "RESPONSE__ERROR_TYPE__RESOURCE_LIMIT", 2000000 },
  { "QUERY_LOGIC", "RESPONSE__ERROR_TYPE__QUERY_LOGIC", 3000000 },
  { "NON_EXISTENCE", "RESPONSE__ERROR_TYPE__NON_EXISTENCE", 3100000 },
  { "OP_FAILED", "RESPONSE__ERROR_TYPE__OP_FAILED", 4100000 },
  { "OP_INDETERMINATE", "RESPONSE__ERROR_TYPE__OP_INDETERMINATE", 4200000 },
  { "USER", "RESPONSE__ERROR_TYPE__USER", 5000000 },
  { "PERMISSION_ERROR", "RESPONSE__ERROR_TYPE__PERMISSION_ERROR", 6000000 },
};
static const ProtobufCIntRange response__error_type__value_ranges[] = {
{1000000, 0},{2000000, 1},{3000000, 2},{3100000, 3},{4100000, 4},{4200000, 5},{5000000, 6},{6000000, 7},{0, 8}
};
static const ProtobufCEnumValueIndex response__error_type__enum_values_by_name[8] =
{
  { "INTERNAL", 0 },
  { "NON_EXISTENCE", 3 },
  { "OP_FAILED", 4 },
  { "OP_INDETERMINATE", 5 },
  { "PERMISSION_ERROR", 7 },
  { "QUERY_LOGIC", 2 },
  { "RESOURCE_LIMIT", 1 },
  { "USER", 6 },
};
const ProtobufCEnumDescriptor response__error_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.ErrorType",
  "ErrorType",
  "Response__ErrorType",
  "",
  8,
  response__error_type__enum_values_by_number,
  8,
  response__error_type__enum_values_by_name,
  8,
  response__error_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue response__response_note__enum_values_by_number[5] =
{
  { "SEQUENCE_FEED", "RESPONSE__RESPONSE_NOTE__SEQUENCE_FEED", 1 },
  { "ATOM_FEED", "RESPONSE__RESPONSE_NOTE__ATOM_FEED", 2 },
  { "ORDER_BY_LIMIT_FEED", "RESPONSE__RESPONSE_NOTE__ORDER_BY_LIMIT_FEED", 3 },
  { "UNIONED_FEED", "RESPONSE__RESPONSE_NOTE__UNIONED_FEED", 4 },
  { "INCLUDES_STATES", "RESPONSE__RESPONSE_NOTE__INCLUDES_STATES", 5 },
};
static const ProtobufCIntRange response__response_note__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex response__response_note__enum_values_by_name[5] =
{
  { "ATOM_FEED", 1 },
  { "INCLUDES_STATES", 4 },
  { "ORDER_BY_LIMIT_FEED", 2 },
  { "SEQUENCE_FEED", 0 },
  { "UNIONED_FEED", 3 },
};
const ProtobufCEnumDescriptor response__response_note__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.ResponseNote",
  "ResponseNote",
  "Response__ResponseNote",
  "",
  5,
  response__response_note__enum_values_by_number,
  5,
  response__response_note__enum_values_by_name,
  1,
  response__response_note__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Response, has_type),
    offsetof(Response, type),
    &response__response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Response, has_token),
    offsetof(Response, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, n_response),
    offsetof(Response, response),
    &datum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backtrace",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, backtrace),
    &backtrace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "profile",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, profile),
    &datum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notes",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Response, n_notes),
    offsetof(Response, notes),
    &response__response_note__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_type",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Response, has_error_type),
    offsetof(Response, error_type),
    &response__error_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = backtrace */
  6,   /* field[6] = error_type */
  5,   /* field[5] = notes */
  4,   /* field[4] = profile */
  2,   /* field[2] = response */
  1,   /* field[1] = token */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  7,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor datum__assoc_pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Datum__AssocPair, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Datum__AssocPair, val),
    &datum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned datum__assoc_pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange datum__assoc_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor datum__assoc_pair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Datum.AssocPair",
  "AssocPair",
  "Datum__AssocPair",
  "",
  sizeof(Datum__AssocPair),
  2,
  datum__assoc_pair__field_descriptors,
  datum__assoc_pair__field_indices_by_name,
  1,  datum__assoc_pair__number_ranges,
  (ProtobufCMessageInit) datum__assoc_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue datum__datum_type__enum_values_by_number[7] =
{
  { "R_NULL", "DATUM__DATUM_TYPE__R_NULL", 1 },
  { "R_BOOL", "DATUM__DATUM_TYPE__R_BOOL", 2 },
  { "R_NUM", "DATUM__DATUM_TYPE__R_NUM", 3 },
  { "R_STR", "DATUM__DATUM_TYPE__R_STR", 4 },
  { "R_ARRAY", "DATUM__DATUM_TYPE__R_ARRAY", 5 },
  { "R_OBJECT", "DATUM__DATUM_TYPE__R_OBJECT", 6 },
  { "R_JSON", "DATUM__DATUM_TYPE__R_JSON", 7 },
};
static const ProtobufCIntRange datum__datum_type__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex datum__datum_type__enum_values_by_name[7] =
{
  { "R_ARRAY", 4 },
  { "R_BOOL", 1 },
  { "R_JSON", 6 },
  { "R_NULL", 0 },
  { "R_NUM", 2 },
  { "R_OBJECT", 5 },
  { "R_STR", 3 },
};
const ProtobufCEnumDescriptor datum__datum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Datum.DatumType",
  "DatumType",
  "Datum__DatumType",
  "",
  7,
  datum__datum_type__enum_values_by_number,
  7,
  datum__datum_type__enum_values_by_name,
  1,
  datum__datum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor datum__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Datum, has_type),
    offsetof(Datum, type),
    &datum__datum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_bool",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Datum, has_r_bool),
    offsetof(Datum, r_bool),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_num",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Datum, has_r_num),
    offsetof(Datum, r_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_str",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Datum, r_str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_array",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Datum, n_r_array),
    offsetof(Datum, r_array),
    &datum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_object",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Datum, n_r_object),
    offsetof(Datum, r_object),
    &datum__assoc_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned datum__field_indices_by_name[] = {
  4,   /* field[4] = r_array */
  1,   /* field[1] = r_bool */
  2,   /* field[2] = r_num */
  5,   /* field[5] = r_object */
  3,   /* field[3] = r_str */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange datum__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor datum__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Datum",
  "Datum",
  "Datum",
  "",
  sizeof(Datum),
  6,
  datum__field_descriptors,
  datum__field_indices_by_name,
  1,  datum__number_ranges,
  (ProtobufCMessageInit) datum__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__assoc_pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Term__AssocPair, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Term__AssocPair, val),
    &term__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__assoc_pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange term__assoc_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor term__assoc_pair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Term.AssocPair",
  "AssocPair",
  "Term__AssocPair",
  "",
  sizeof(Term__AssocPair),
  2,
  term__assoc_pair__field_descriptors,
  term__assoc_pair__field_indices_by_name,
  1,  term__assoc_pair__number_ranges,
  (ProtobufCMessageInit) term__assoc_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue term__term_type__enum_values_by_number[186] =
{
  { "DATUM", "TERM__TERM_TYPE__DATUM", 1 },
  { "MAKE_ARRAY", "TERM__TERM_TYPE__MAKE_ARRAY", 2 },
  { "MAKE_OBJ", "TERM__TERM_TYPE__MAKE_OBJ", 3 },
  { "VAR", "TERM__TERM_TYPE__VAR", 10 },
  { "JAVASCRIPT", "TERM__TERM_TYPE__JAVASCRIPT", 11 },
  { "ERROR", "TERM__TERM_TYPE__ERROR", 12 },
  { "IMPLICIT_VAR", "TERM__TERM_TYPE__IMPLICIT_VAR", 13 },
  { "DB", "TERM__TERM_TYPE__DB", 14 },
  { "TABLE", "TERM__TERM_TYPE__TABLE", 15 },
  { "GET", "TERM__TERM_TYPE__GET", 16 },
  { "EQ", "TERM__TERM_TYPE__EQ", 17 },
  { "NE", "TERM__TERM_TYPE__NE", 18 },
  { "LT", "TERM__TERM_TYPE__LT", 19 },
  { "LE", "TERM__TERM_TYPE__LE", 20 },
  { "GT", "TERM__TERM_TYPE__GT", 21 },
  { "GE", "TERM__TERM_TYPE__GE", 22 },
  { "NOT", "TERM__TERM_TYPE__NOT", 23 },
  { "ADD", "TERM__TERM_TYPE__ADD", 24 },
  { "SUB", "TERM__TERM_TYPE__SUB", 25 },
  { "MUL", "TERM__TERM_TYPE__MUL", 26 },
  { "DIV", "TERM__TERM_TYPE__DIV", 27 },
  { "MOD", "TERM__TERM_TYPE__MOD", 28 },
  { "APPEND", "TERM__TERM_TYPE__APPEND", 29 },
  { "SLICE", "TERM__TERM_TYPE__SLICE", 30 },
  { "GET_FIELD", "TERM__TERM_TYPE__GET_FIELD", 31 },
  { "HAS_FIELDS", "TERM__TERM_TYPE__HAS_FIELDS", 32 },
  { "PLUCK", "TERM__TERM_TYPE__PLUCK", 33 },
  { "WITHOUT", "TERM__TERM_TYPE__WITHOUT", 34 },
  { "MERGE", "TERM__TERM_TYPE__MERGE", 35 },
  { "BETWEEN_DEPRECATED", "TERM__TERM_TYPE__BETWEEN_DEPRECATED", 36 },
  { "REDUCE", "TERM__TERM_TYPE__REDUCE", 37 },
  { "MAP", "TERM__TERM_TYPE__MAP", 38 },
  { "FILTER", "TERM__TERM_TYPE__FILTER", 39 },
  { "CONCAT_MAP", "TERM__TERM_TYPE__CONCAT_MAP", 40 },
  { "ORDER_BY", "TERM__TERM_TYPE__ORDER_BY", 41 },
  { "DISTINCT", "TERM__TERM_TYPE__DISTINCT", 42 },
  { "COUNT", "TERM__TERM_TYPE__COUNT", 43 },
  { "UNION", "TERM__TERM_TYPE__UNION", 44 },
  { "NTH", "TERM__TERM_TYPE__NTH", 45 },
  { "INNER_JOIN", "TERM__TERM_TYPE__INNER_JOIN", 48 },
  { "OUTER_JOIN", "TERM__TERM_TYPE__OUTER_JOIN", 49 },
  { "EQ_JOIN", "TERM__TERM_TYPE__EQ_JOIN", 50 },
  { "COERCE_TO", "TERM__TERM_TYPE__COERCE_TO", 51 },
  { "TYPE_OF", "TERM__TERM_TYPE__TYPE_OF", 52 },
  { "UPDATE", "TERM__TERM_TYPE__UPDATE", 53 },
  { "DELETE", "TERM__TERM_TYPE__DELETE", 54 },
  { "REPLACE", "TERM__TERM_TYPE__REPLACE", 55 },
  { "INSERT", "TERM__TERM_TYPE__INSERT", 56 },
  { "DB_CREATE", "TERM__TERM_TYPE__DB_CREATE", 57 },
  { "DB_DROP", "TERM__TERM_TYPE__DB_DROP", 58 },
  { "DB_LIST", "TERM__TERM_TYPE__DB_LIST", 59 },
  { "TABLE_CREATE", "TERM__TERM_TYPE__TABLE_CREATE", 60 },
  { "TABLE_DROP", "TERM__TERM_TYPE__TABLE_DROP", 61 },
  { "TABLE_LIST", "TERM__TERM_TYPE__TABLE_LIST", 62 },
  { "FUNCALL", "TERM__TERM_TYPE__FUNCALL", 64 },
  { "BRANCH", "TERM__TERM_TYPE__BRANCH", 65 },
  { "OR", "TERM__TERM_TYPE__OR", 66 },
  { "AND", "TERM__TERM_TYPE__AND", 67 },
  { "FOR_EACH", "TERM__TERM_TYPE__FOR_EACH", 68 },
  { "FUNC", "TERM__TERM_TYPE__FUNC", 69 },
  { "SKIP", "TERM__TERM_TYPE__SKIP", 70 },
  { "LIMIT", "TERM__TERM_TYPE__LIMIT", 71 },
  { "ZIP", "TERM__TERM_TYPE__ZIP", 72 },
  { "ASC", "TERM__TERM_TYPE__ASC", 73 },
  { "DESC", "TERM__TERM_TYPE__DESC", 74 },
  { "INDEX_CREATE", "TERM__TERM_TYPE__INDEX_CREATE", 75 },
  { "INDEX_DROP", "TERM__TERM_TYPE__INDEX_DROP", 76 },
  { "INDEX_LIST", "TERM__TERM_TYPE__INDEX_LIST", 77 },
  { "GET_ALL", "TERM__TERM_TYPE__GET_ALL", 78 },
  { "INFO", "TERM__TERM_TYPE__INFO", 79 },
  { "PREPEND", "TERM__TERM_TYPE__PREPEND", 80 },
  { "SAMPLE", "TERM__TERM_TYPE__SAMPLE", 81 },
  { "INSERT_AT", "TERM__TERM_TYPE__INSERT_AT", 82 },
  { "DELETE_AT", "TERM__TERM_TYPE__DELETE_AT", 83 },
  { "CHANGE_AT", "TERM__TERM_TYPE__CHANGE_AT", 84 },
  { "SPLICE_AT", "TERM__TERM_TYPE__SPLICE_AT", 85 },
  { "IS_EMPTY", "TERM__TERM_TYPE__IS_EMPTY", 86 },
  { "OFFSETS_OF", "TERM__TERM_TYPE__OFFSETS_OF", 87 },
  { "SET_INSERT", "TERM__TERM_TYPE__SET_INSERT", 88 },
  { "SET_INTERSECTION", "TERM__TERM_TYPE__SET_INTERSECTION", 89 },
  { "SET_UNION", "TERM__TERM_TYPE__SET_UNION", 90 },
  { "SET_DIFFERENCE", "TERM__TERM_TYPE__SET_DIFFERENCE", 91 },
  { "DEFAULT", "TERM__TERM_TYPE__DEFAULT", 92 },
  { "CONTAINS", "TERM__TERM_TYPE__CONTAINS", 93 },
  { "KEYS", "TERM__TERM_TYPE__KEYS", 94 },
  { "DIFFERENCE", "TERM__TERM_TYPE__DIFFERENCE", 95 },
  { "WITH_FIELDS", "TERM__TERM_TYPE__WITH_FIELDS", 96 },
  { "MATCH", "TERM__TERM_TYPE__MATCH", 97 },
  { "JSON", "TERM__TERM_TYPE__JSON", 98 },
  { "ISO8601", "TERM__TERM_TYPE__ISO8601", 99 },
  { "TO_ISO8601", "TERM__TERM_TYPE__TO_ISO8601", 100 },
  { "EPOCH_TIME", "TERM__TERM_TYPE__EPOCH_TIME", 101 },
  { "TO_EPOCH_TIME", "TERM__TERM_TYPE__TO_EPOCH_TIME", 102 },
  { "NOW", "TERM__TERM_TYPE__NOW", 103 },
  { "IN_TIMEZONE", "TERM__TERM_TYPE__IN_TIMEZONE", 104 },
  { "DURING", "TERM__TERM_TYPE__DURING", 105 },
  { "DATE", "TERM__TERM_TYPE__DATE", 106 },
  { "MONDAY", "TERM__TERM_TYPE__MONDAY", 107 },
  { "TUESDAY", "TERM__TERM_TYPE__TUESDAY", 108 },
  { "WEDNESDAY", "TERM__TERM_TYPE__WEDNESDAY", 109 },
  { "THURSDAY", "TERM__TERM_TYPE__THURSDAY", 110 },
  { "FRIDAY", "TERM__TERM_TYPE__FRIDAY", 111 },
  { "SATURDAY", "TERM__TERM_TYPE__SATURDAY", 112 },
  { "SUNDAY", "TERM__TERM_TYPE__SUNDAY", 113 },
  { "JANUARY", "TERM__TERM_TYPE__JANUARY", 114 },
  { "FEBRUARY", "TERM__TERM_TYPE__FEBRUARY", 115 },
  { "MARCH", "TERM__TERM_TYPE__MARCH", 116 },
  { "APRIL", "TERM__TERM_TYPE__APRIL", 117 },
  { "MAY", "TERM__TERM_TYPE__MAY", 118 },
  { "JUNE", "TERM__TERM_TYPE__JUNE", 119 },
  { "JULY", "TERM__TERM_TYPE__JULY", 120 },
  { "AUGUST", "TERM__TERM_TYPE__AUGUST", 121 },
  { "SEPTEMBER", "TERM__TERM_TYPE__SEPTEMBER", 122 },
  { "OCTOBER", "TERM__TERM_TYPE__OCTOBER", 123 },
  { "NOVEMBER", "TERM__TERM_TYPE__NOVEMBER", 124 },
  { "DECEMBER", "TERM__TERM_TYPE__DECEMBER", 125 },
  { "TIME_OF_DAY", "TERM__TERM_TYPE__TIME_OF_DAY", 126 },
  { "TIMEZONE", "TERM__TERM_TYPE__TIMEZONE", 127 },
  { "YEAR", "TERM__TERM_TYPE__YEAR", 128 },
  { "MONTH", "TERM__TERM_TYPE__MONTH", 129 },
  { "DAY", "TERM__TERM_TYPE__DAY", 130 },
  { "DAY_OF_WEEK", "TERM__TERM_TYPE__DAY_OF_WEEK", 131 },
  { "DAY_OF_YEAR", "TERM__TERM_TYPE__DAY_OF_YEAR", 132 },
  { "HOURS", "TERM__TERM_TYPE__HOURS", 133 },
  { "MINUTES", "TERM__TERM_TYPE__MINUTES", 134 },
  { "SECONDS", "TERM__TERM_TYPE__SECONDS", 135 },
  { "TIME", "TERM__TERM_TYPE__TIME", 136 },
  { "LITERAL", "TERM__TERM_TYPE__LITERAL", 137 },
  { "SYNC", "TERM__TERM_TYPE__SYNC", 138 },
  { "INDEX_STATUS", "TERM__TERM_TYPE__INDEX_STATUS", 139 },
  { "INDEX_WAIT", "TERM__TERM_TYPE__INDEX_WAIT", 140 },
  { "UPCASE", "TERM__TERM_TYPE__UPCASE", 141 },
  { "DOWNCASE", "TERM__TERM_TYPE__DOWNCASE", 142 },
  { "OBJECT", "TERM__TERM_TYPE__OBJECT", 143 },
  { "GROUP", "TERM__TERM_TYPE__GROUP", 144 },
  { "SUM", "TERM__TERM_TYPE__SUM", 145 },
  { "AVG", "TERM__TERM_TYPE__AVG", 146 },
  { "MIN", "TERM__TERM_TYPE__MIN", 147 },
  { "MAX", "TERM__TERM_TYPE__MAX", 148 },
  { "SPLIT", "TERM__TERM_TYPE__SPLIT", 149 },
  { "UNGROUP", "TERM__TERM_TYPE__UNGROUP", 150 },
  { "RANDOM", "TERM__TERM_TYPE__RANDOM", 151 },
  { "CHANGES", "TERM__TERM_TYPE__CHANGES", 152 },
  { "HTTP", "TERM__TERM_TYPE__HTTP", 153 },
  { "ARGS", "TERM__TERM_TYPE__ARGS", 154 },
  { "BINARY", "TERM__TERM_TYPE__BINARY", 155 },
  { "INDEX_RENAME", "TERM__TERM_TYPE__INDEX_RENAME", 156 },
  { "GEOJSON", "TERM__TERM_TYPE__GEOJSON", 157 },
  { "TO_GEOJSON", "TERM__TERM_TYPE__TO_GEOJSON", 158 },
  { "POINT", "TERM__TERM_TYPE__POINT", 159 },
  { "LINE", "TERM__TERM_TYPE__LINE", 160 },
  { "POLYGON", "TERM__TERM_TYPE__POLYGON", 161 },
  { "DISTANCE", "TERM__TERM_TYPE__DISTANCE", 162 },
  { "INTERSECTS", "TERM__TERM_TYPE__INTERSECTS", 163 },
  { "INCLUDES", "TERM__TERM_TYPE__INCLUDES", 164 },
  { "CIRCLE", "TERM__TERM_TYPE__CIRCLE", 165 },
  { "GET_INTERSECTING", "TERM__TERM_TYPE__GET_INTERSECTING", 166 },
  { "FILL", "TERM__TERM_TYPE__FILL", 167 },
  { "GET_NEAREST", "TERM__TERM_TYPE__GET_NEAREST", 168 },
  { "UUID", "TERM__TERM_TYPE__UUID", 169 },
  { "BRACKET", "TERM__TERM_TYPE__BRACKET", 170 },
  { "POLYGON_SUB", "TERM__TERM_TYPE__POLYGON_SUB", 171 },
  { "TO_JSON_STRING", "TERM__TERM_TYPE__TO_JSON_STRING", 172 },
  { "RANGE", "TERM__TERM_TYPE__RANGE", 173 },
  { "CONFIG", "TERM__TERM_TYPE__CONFIG", 174 },
  { "STATUS", "TERM__TERM_TYPE__STATUS", 175 },
  { "RECONFIGURE", "TERM__TERM_TYPE__RECONFIGURE", 176 },
  { "WAIT", "TERM__TERM_TYPE__WAIT", 177 },
  { "REBALANCE", "TERM__TERM_TYPE__REBALANCE", 179 },
  { "MINVAL", "TERM__TERM_TYPE__MINVAL", 180 },
  { "MAXVAL", "TERM__TERM_TYPE__MAXVAL", 181 },
  { "BETWEEN", "TERM__TERM_TYPE__BETWEEN", 182 },
  { "FLOOR", "TERM__TERM_TYPE__FLOOR", 183 },
  { "CEIL", "TERM__TERM_TYPE__CEIL", 184 },
  { "ROUND", "TERM__TERM_TYPE__ROUND", 185 },
  { "VALUES", "TERM__TERM_TYPE__VALUES", 186 },
  { "FOLD", "TERM__TERM_TYPE__FOLD", 187 },
  { "GRANT", "TERM__TERM_TYPE__GRANT", 188 },
  { "SET_WRITE_HOOK", "TERM__TERM_TYPE__SET_WRITE_HOOK", 189 },
  { "GET_WRITE_HOOK", "TERM__TERM_TYPE__GET_WRITE_HOOK", 190 },
  { "BIT_AND", "TERM__TERM_TYPE__BIT_AND", 191 },
  { "BIT_OR", "TERM__TERM_TYPE__BIT_OR", 192 },
  { "BIT_XOR", "TERM__TERM_TYPE__BIT_XOR", 193 },
  { "BIT_NOT", "TERM__TERM_TYPE__BIT_NOT", 194 },
  { "BIT_SAL", "TERM__TERM_TYPE__BIT_SAL", 195 },
  { "BIT_SAR", "TERM__TERM_TYPE__BIT_SAR", 196 },
};
static const ProtobufCIntRange term__term_type__value_ranges[] = {
{1, 0},{10, 3},{48, 39},{64, 54},{179, 168},{0, 186}
};
static const ProtobufCEnumValueIndex term__term_type__enum_values_by_name[186] =
{
  { "ADD", 17 },
  { "AND", 57 },
  { "APPEND", 22 },
  { "APRIL", 107 },
  { "ARGS", 144 },
  { "ASC", 63 },
  { "AUGUST", 111 },
  { "AVG", 136 },
  { "BETWEEN", 171 },
  { "BETWEEN_DEPRECATED", 29 },
  { "BINARY", 145 },
  { "BIT_AND", 180 },
  { "BIT_NOT", 183 },
  { "BIT_OR", 181 },
  { "BIT_SAL", 184 },
  { "BIT_SAR", 185 },
  { "BIT_XOR", 182 },
  { "BRACKET", 160 },
  { "BRANCH", 55 },
  { "CEIL", 173 },
  { "CHANGES", 142 },
  { "CHANGE_AT", 74 },
  { "CIRCLE", 155 },
  { "COERCE_TO", 42 },
  { "CONCAT_MAP", 33 },
  { "CONFIG", 164 },
  { "CONTAINS", 83 },
  { "COUNT", 36 },
  { "DATE", 96 },
  { "DATUM", 0 },
  { "DAY", 120 },
  { "DAY_OF_WEEK", 121 },
  { "DAY_OF_YEAR", 122 },
  { "DB", 7 },
  { "DB_CREATE", 48 },
  { "DB_DROP", 49 },
  { "DB_LIST", 50 },
  { "DECEMBER", 115 },
  { "DEFAULT", 82 },
  { "DELETE", 45 },
  { "DELETE_AT", 73 },
  { "DESC", 64 },
  { "DIFFERENCE", 85 },
  { "DISTANCE", 152 },
  { "DISTINCT", 35 },
  { "DIV", 20 },
  { "DOWNCASE", 132 },
  { "DURING", 95 },
  { "EPOCH_TIME", 91 },
  { "EQ", 10 },
  { "EQ_JOIN", 41 },
  { "ERROR", 5 },
  { "FEBRUARY", 105 },
  { "FILL", 157 },
  { "FILTER", 32 },
  { "FLOOR", 172 },
  { "FOLD", 176 },
  { "FOR_EACH", 58 },
  { "FRIDAY", 101 },
  { "FUNC", 59 },
  { "FUNCALL", 54 },
  { "GE", 15 },
  { "GEOJSON", 147 },
  { "GET", 9 },
  { "GET_ALL", 68 },
  { "GET_FIELD", 24 },
  { "GET_INTERSECTING", 156 },
  { "GET_NEAREST", 158 },
  { "GET_WRITE_HOOK", 179 },
  { "GRANT", 177 },
  { "GROUP", 134 },
  { "GT", 14 },
  { "HAS_FIELDS", 25 },
  { "HOURS", 123 },
  { "HTTP", 143 },
  { "IMPLICIT_VAR", 6 },
  { "INCLUDES", 154 },
  { "INDEX_CREATE", 65 },
  { "INDEX_DROP", 66 },
  { "INDEX_LIST", 67 },
  { "INDEX_RENAME", 146 },
  { "INDEX_STATUS", 129 },
  { "INDEX_WAIT", 130 },
  { "INFO", 69 },
  { "INNER_JOIN", 39 },
  { "INSERT", 47 },
  { "INSERT_AT", 72 },
  { "INTERSECTS", 153 },
  { "IN_TIMEZONE", 94 },
  { "ISO8601", 89 },
  { "IS_EMPTY", 76 },
  { "JANUARY", 104 },
  { "JAVASCRIPT", 4 },
  { "JSON", 88 },
  { "JULY", 110 },
  { "JUNE", 109 },
  { "KEYS", 84 },
  { "LE", 13 },
  { "LIMIT", 61 },
  { "LINE", 150 },
  { "LITERAL", 127 },
  { "LT", 12 },
  { "MAKE_ARRAY", 1 },
  { "MAKE_OBJ", 2 },
  { "MAP", 31 },
  { "MARCH", 106 },
  { "MATCH", 87 },
  { "MAX", 138 },
  { "MAXVAL", 170 },
  { "MAY", 108 },
  { "MERGE", 28 },
  { "MIN", 137 },
  { "MINUTES", 124 },
  { "MINVAL", 169 },
  { "MOD", 21 },
  { "MONDAY", 97 },
  { "MONTH", 119 },
  { "MUL", 19 },
  { "NE", 11 },
  { "NOT", 16 },
  { "NOVEMBER", 114 },
  { "NOW", 93 },
  { "NTH", 38 },
  { "OBJECT", 133 },
  { "OCTOBER", 113 },
  { "OFFSETS_OF", 77 },
  { "OR", 56 },
  { "ORDER_BY", 34 },
  { "OUTER_JOIN", 40 },
  { "PLUCK", 26 },
  { "POINT", 149 },
  { "POLYGON", 151 },
  { "POLYGON_SUB", 161 },
  { "PREPEND", 70 },
  { "RANDOM", 141 },
  { "RANGE", 163 },
  { "REBALANCE", 168 },
  { "RECONFIGURE", 166 },
  { "REDUCE", 30 },
  { "REPLACE", 46 },
  { "ROUND", 174 },
  { "SAMPLE", 71 },
  { "SATURDAY", 102 },
  { "SECONDS", 125 },
  { "SEPTEMBER", 112 },
  { "SET_DIFFERENCE", 81 },
  { "SET_INSERT", 78 },
  { "SET_INTERSECTION", 79 },
  { "SET_UNION", 80 },
  { "SET_WRITE_HOOK", 178 },
  { "SKIP", 60 },
  { "SLICE", 23 },
  { "SPLICE_AT", 75 },
  { "SPLIT", 139 },
  { "STATUS", 165 },
  { "SUB", 18 },
  { "SUM", 135 },
  { "SUNDAY", 103 },
  { "SYNC", 128 },
  { "TABLE", 8 },
  { "TABLE_CREATE", 51 },
  { "TABLE_DROP", 52 },
  { "TABLE_LIST", 53 },
  { "THURSDAY", 100 },
  { "TIME", 126 },
  { "TIMEZONE", 117 },
  { "TIME_OF_DAY", 116 },
  { "TO_EPOCH_TIME", 92 },
  { "TO_GEOJSON", 148 },
  { "TO_ISO8601", 90 },
  { "TO_JSON_STRING", 162 },
  { "TUESDAY", 98 },
  { "TYPE_OF", 43 },
  { "UNGROUP", 140 },
  { "UNION", 37 },
  { "UPCASE", 131 },
  { "UPDATE", 44 },
  { "UUID", 159 },
  { "VALUES", 175 },
  { "VAR", 3 },
  { "WAIT", 167 },
  { "WEDNESDAY", 99 },
  { "WITHOUT", 27 },
  { "WITH_FIELDS", 86 },
  { "YEAR", 118 },
  { "ZIP", 62 },
};
const ProtobufCEnumDescriptor term__term_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Term.TermType",
  "TermType",
  "Term__TermType",
  "",
  186,
  term__term_type__enum_values_by_number,
  186,
  term__term_type__enum_values_by_name,
  5,
  term__term_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor term__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Term, has_type),
    offsetof(Term, type),
    &term__term_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Term, datum),
    &datum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Term, n_args),
    offsetof(Term, args),
    &term__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optargs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Term, n_optargs),
    offsetof(Term, optargs),
    &term__assoc_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__field_indices_by_name[] = {
  2,   /* field[2] = args */
  1,   /* field[1] = datum */
  3,   /* field[3] = optargs */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange term__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor term__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Term",
  "Term",
  "Term",
  "",
  sizeof(Term),
  4,
  term__field_descriptors,
  term__field_indices_by_name,
  1,  term__number_ranges,
  (ProtobufCMessageInit) term__init,
  NULL,NULL,NULL    /* reserved[123] */
};
